config/routes.rb
Rails.application.routes.draw do
  devise_for :users

root 'static_pages#main_page'

resources "tweets"

match 'processform', to: 'tweets#process_form_to_follow_user', as: :process_form_to_follow_user, via: [:post]

get 'myprofile', to: 'static_pages#my_profile_page', as: "my_profile_page"

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
	validates :content, length: { maximum: 140 }
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   has_many :tweets

   has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy

	has_many :passive_relationships, class_name:  "Relationship",
	                   foreign_key: "followed_id",
	                   dependent:   :destroy

  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # Unfollows a user.
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following the other user.
  def following?(other_user)
    following.include?(other_user)
  end
	#mounting user for carrierwave
	mount_uploader :picture, PictureUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_filter :configure_devise_params, if: :devise_controller?
  protect_from_forgery with: :exception


	def configure_devise_params
		devise_parameter_sanitizer.for(:sign_up) do |u|
	  		u.permit(:email, :password, :password_confirmation, :picture)
	  	end
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def main_page
		
	end

	def about_us
	end

	def contact_us
	end

	def my_profile_page
	end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

	before_action :authenticate_user!

	def new
		@tweet = Tweet.new
		@tweets = Tweet.all
	end

	def create
		@tweet_to_create = Tweet.new(tweet_params)
		@tweet_to_create.user = current_user
		if @tweet_to_create.save
			flash.now["success"] = "You have created a tweet!"
		else
			flash.now["danger"] = "Please review the errors below."
		end

		@tweet = Tweet.new
		
		@tweets = Tweet.all
		print "the tweet is " + @tweet.inspect.to_s
		
		render 'new'
	end

	def edit
	end

	def show
	end

	def process_form_to_follow_user
		@users = User.all.reject{|user| user == current_user}
		@user = User.find(params["user"]["user_to_follow"])

		if params["unfollow"]
			current_user.unfollow(@user)
		elsif params["follow"]
			current_user.follow(@user)
		end

		render 'index'
	end

	def index
		@users = User.all.reject{|user| user == current_user}
	end

	def tweet_params
		params.require("tweet").permit("content")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyFirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Twipper", root_path, class: "navbar-brand"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to "New Tweet Page", new_tweet_path%></li>
        <li><%= link_to "Users", tweets_path%></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
      	<% if user_signed_in? %>
        <li><%= link_to 'My Profile', my_profile_page_path %></li>
        	<li><%= link_to "Log Out", destroy_user_session_path, method: "delete" %></li>
        <% else %>
        	<li><%= link_to "Sign Up", new_user_registration_path %></li>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

<div class = "container">
<% flash.each do |key, value| %>
	<div class = "alert alert-<%= key %>">
		<%= value %>
	</div>
<% end %>
<%= yield %>
</div>

</body>
</html>

app/views/static_pages/main_page.html.erb
Is this the main page, is this just fantasy? I'm just some poor code...

app/views/static_pages/my_profile_page.html.erb
My Profile Page

<%= image_tag current_user.picture %>

<% current_user.tweets.each do |tweet| %>
		<%= tweet.content %> <br>
<% end %>

app/views/tweets/index.html.erb
<% @users.each do |user|  %>
	<%= simple_form_for user, url: process_form_to_follow_user_path, method: :post do |f| %>
		<%= user.email %>
		<%= f.input "user_to_follow", as: "hidden", input_html: {value: user.id} %>
		<% if current_user.following?(user) %>
			<%= f.submit "Unfollow", class: "btn btn-danger", name: "unfollow" %>
		<% else %>
		<%= f.submit "Follow", class: "btn btn-primary", name: "follow" %>
		<% end %>
	<% end %><br>
<% end %>

app/views/tweets/new.html.erb
<p>Here's a new tweet page.</p>

<%= simple_form_for @tweet, url: tweets_path, method: 'post' do |t| %>
	<%= t.input :content %>
	<%= t.button :submit %>
<% end %>

<% @tweets.each do |tweet| %>
	<%= tweet.content %><br />
<% end %>